vulnerability_id: CVE-2019-18874
notes:
- text: psutil (aka python-psutil) through 5.6.5 can have a double free. This occurs because of refcount mishandling within a while or for loop that converts system data into a Python object.
artifacts:
- id: pkg:maven/psutil/psutil@5.4.6
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.4.7
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.6.5
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.6.2
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.6.3
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.4.8
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.6.0
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.5.1
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.4.2
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.6.1
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.4.3
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.2.2
  reason: Reviewed manually
  affected: true
- id: pkg:maven/psutil/psutil@5.5.0
  reason: Reviewed manually
  affected: true
